version: '3.7'

services:

  training-service:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    user: "${USER_ID:-root}"
    environment:
      TF_FORCE_GPU_ALLOW_GROWTH: "true"
    volumes:
      - ./src/:/usr/src/app/src/
      - ./data:/usr/src/app/data/
      - ./models:/usr/src/app/models/
      - ./results:/usr/src/app/results/
    command: [ "bash" ]


